version: '3.0'

networks:
  bridge:
    external: true

services: 
    obj-detection:
        network_mode: bridge
        image: "ealtedge/obj-detection:v1.0"
        restart: always
        ports: 
            - "9998:9998"
        container_name: obj-detection
        hostname: obj-detection

    node-proxy:
        network_mode: bridge
        image: ealtedge/robo-node-proxy:v1.0
        ports: 
            - "30999:5000"
        container_name: node-proxy
        hostname: node-proxy

    smart-shelf:
        network_mode: bridge
        image: "ealtedge/smartshelf:v1.0"
        ports: 
            - "30995:9995"
        container_name: smart-shelf
        hostname: smart-shelf
        depends_on: 
            - obj-detection
            - node-proxy
        links:
        - obj-detection:obj-detection
        - node-proxy:node-proxy

    robo-fe:
        network_mode: bridge
        image: ealtedge/robo-fe:v1.0
        ports: 
            - "30997:8080"
        container_name: robo-fe
        hostname: robo-fe
        depends_on: 
            - node-proxy
            - smart-shelf
        links:
        - node-proxy:node-proxy    
        - smart-shelf:smart-shelf




