---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcb-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pcbui
  template:
    metadata:
      labels:
        app: pcbui
    spec:
      containers:
        - name: pcbui
          image: ealtedge/pcbui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pcbui-service
spec:
  type: NodePort
  selector:
    app: pcbui
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 80
      nodePort: 30002
